#!/bin/bash
# Run a vagrant $command ($1) on a vagrant $server ($2)

# Cache vagrant global-status output in file
file="$HOME/.globvag"
# Create cache file if it doesn't exist
if [[ ! ( -e $file ) ]]
  then vagrant global-status --prune > $file
fi

# Refresh the file if older than 1800 seconds
if [[ ! ( $(stat --format=%Y $file) -le $(( $(date +%s) - 1800 )) ) ]]
  then 
  vagrant global-status --prune > $file
fi

vagrant $1 $( cat $file | grep $2 | cut -d' ' -f1 ) && exit 0
exit 1
